---
- hosts: localhosts
  become: true
  tasks:
    - name: Instalar devecot
      dnf: 
      name: tree
      state: latests
      
    - name: Subir Servicio de Apache
      sistemd: 
      name: httpd
      state: started  
...
